  - name: Copying mango repo
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/
          
  - name: Installing MongoDB
    ansible.builtin.dnf:
     name : mongodb-org
     state : present
     
  - name: Replace the local-host
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0' 
  - name: Start the mongodb services
    ansible.builtin.service:
      name : mongod
      state : started
      enabled : yes
          

