- name: Setup Catalogue
  hosts: catalogue
  become: yes
  tasks:

  - name: enable current nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
 
  - name: Installing nodejs
    ansible.builtin.dnf:
     name: nodejs
     state : present
 
  - name: Adding user
    ansible.builtin.user:
      name: roboshop
      comment: "roboshop system user"
      system: true
      home : /app
      shell: /sbin/nologin
 
  - name: Deleting directory
    ansible.builtin.file:
      path : /app
      state: absent
 
  - name: Creating directory
    ansible.builtin.file:
      path : /app
      state: directory  
  
  - name: deleting catalogue.zip 
    ansible.builtin.file:
      path : /tmp/catalogue.zip
      state: absent
  
  - name: Downloading the application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
  
  - name: unzip the code
    ansible.builtin.unarchive:
      src : /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  - name: Install catalogue node.js package
    community.general.npm:
      path: /app
  
  -  name: Force systemd to reread configs 
     ansible.builtin.systemd_service:
      daemon_reload: true
  
  -  name: copy catalogue service
     ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service
  
  - name: Copying mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

  - name: check if data is already loaded or not
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: loading data to mangodb
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" < /app/db/master-data.js  
    when: catalogue_output.stdout | int < 0

  -  name: Start the catalogue services
     ansible.builtin.service:
        name : catalogue
        state : restarted
        enabled : yes
 