- name: Setup MongoDB
  hosts: mongodb
  become : yes
  tasks:

  - name: Copying mango repo
    ansible.builtin.copy:
      src: mango.repo
      dest: /etc/yum.repos.d/
      remote_src: yes
  - name: Installing MongoDB
    ansible.builtin.dnf:
      name : MongoDB
      state : present
  - name: Replace the local-host
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0' 
  - name: Start the mongodb services
    ansible.builtin.service:
        name : MongoDB
        state : started
        enabled : yes
        


