- name : Learning conitions in ansi
  hosts : local
  connection : local
  vars_prompt:
   - name: i
     prompt : "enter the value"
     private : false
  tasks : 
   - name : check condition
     ansible.builtin.debug:
       msg: "Enterd value {{ i }} is a postive number"
     when : i > 0 
   