- name : Learning conitions in ansi
  hosts : local
  connection : local
  vars_prompt:
   - name: i
     prompt : "enter the value"
     private : false
  tasks : 
   - name : check vale is positive
     ansible.builtin.debug:
       msg: "Enterd value {{ i }} is a postive number"
     when : i | int > 0 
   
   - name : check value is negative or 0
     ansible.builtin.debug:
       msg: "Enterd value {{ i }} is either a negative number or a 0"
     when : i | int < 0
    
   - name : check value is negative or 0
     ansible.builtin.debug:
       msg: "You have entered {{ i }}"
     when : i | int == 0