- name: Installation
  hosts: all
  become: true
  tasks:
   - name: Install Nginx
     ansible.builtin.package:
      name : nginx
      state: present
   - name: Enable Nginx
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

     