- name : learning loops in ansi
  hosts : local
  connection : local    
  tasks :
  - name : looping through names
    ansible.builtin.debug:
       msg: "There are my favourite celebrities : {{ item }}"
    loop:
     - Mahesh babu
     - MS Dhoni
     - Keerthi suresh

