- name : Install only selected packages
  hosts : local
  connection : local
  become : yes
  tasks:
  - name : Intalling 
    ansible.builtin.package:
     name : "{{ item.name }}"
     state : "{{ item.state  }}"
    loop:
      - name : "nginx", state : "absent"  
      - name : "mysql", state : "present"
      - name : "zip", state : "absent"