- name : learning loops in ansi
  hosts : local
  connection : local  
  become : yes  
  tasks :
  # - name : looping through names
  #   ansible.builtin.debug:
  #      msg: "There are my favourite celebrities : {{ item }}"
  #   loop:
  #    - Mahesh babu
  #    - MS Dhoni
  #    - Keerthi suresh
     - name : Install applications
       ansible.builtin.package:    
        name : "{{ item }}"
        state : present
       loop:
        - nginx
        - mysql
        - python 

