- name : Vairable Presidence
  hosts: local
  connection: local
  vars:
   txt: "a play level variable"
  # vars_files:
  #  - vars-play
  vars_prompt:
   - name : txt
     prompt : "please enter txt"
     private : false
  tasks:
   - name: Proof of variable Presidence
    #  vars:
    #   txt: "a task level variable"
     ansible.builtin.debug:
      msg: "This is from {{ txt }}"
   
