- name : settingup app
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup.yaml

- name : installing nodejs
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs-setup.yaml

- name : setting systemd
  ansible.builtin.import_role:
   name : common
   tasks_from : systemd-setup.yaml

- name: starting cart
  ansible.builtin.service:
    name : cart
    state: restarted
    enabled: yes