ansible_user : ec2-user
ansible_password : DevOps321
MONGODB_HOST : mongodb.mbops.online
CATALOGUE_HOST: catalogue.mbops.online
REDIS_HOST : redis.mbops.online
USER_HOST: user.mbops.online
CART_HOST: cart.mbops.online
MYSQL_HOST: mysql.mbops.online
SHIPPING_HOST: shipping.mbops.online
RABBITMQ_HOST : rabbitmq.mbops.online
PAYMENT_HOST : payment.mbops.online